# Generated by Django 4.2.7 on 2023-11-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bsk_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="korean_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
