# Generated by Django 4.2.7 on 2023-11-25 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bsk_app", "0002_userprofile_korean_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowerPot",
            fields=[
                ("pot_number", models.AutoField(primary_key=True, serialize=False)),
                ("plant_name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("plant_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "moisture_level",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
        ),
    ]
