# Generated by Django 4.2.7 on 2023-11-25 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("bsk_app", "0003_flowerpot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="flower_pot_number",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="flower_pot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bsk_app.flowerpot",
            ),
        ),
    ]
